name: Bot Run

on:
    schedule:
      - cron: '0 23 * * *' # 8時
      - cron: '0 5 * * *'  # 14時
      - cron: '0 11 * * *' # 20時
      - cron: '0 17 * * *' # 2時

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
                node-version: "20"
          - run: |
              cd discord-app && 
              echo "${{ secrets.ENV_VALUES }}" > .env && 
              npm install && 
              npm install sequelize-cli && 
              npx tsc -p . && 
              npx sequelize-cli db:migrate --env production && 
              cd .. & 
              docker compose -f docker-compose.prod.yml up -d && 
              docker logs discord-app -f
            env:
              POSTGRES_DB_UNITTEST: ${{ secrets.POSTGRES_DB_UNITTEST }}
              POSTGRES_PASSWORD_UNITTEST: ${{ secrets.POSTGRES_PASSWORD_UNITTEST }}
              POSTGRES_USER_UNITTEST: ${{ secrets.POSTGRES_USER_UNITTEST }}
              POSTGRES_DB_DEVELOPMENT: ${{ secrets.POSTGRES_DB_DEVELOPMENT }}
              POSTGRES_PASSWORD_DEVELOPMENT: ${{ secrets.POSTGRES_PASSWORD_DEVELOPMENT }}
              POSTGRES_USER_DEVELOPMENT: ${{ secrets.POSTGRES_USER_DEVELOPMENT }}
